export const STATUS_CODE_SUCCESS = 200;
export const STATUS_CODE_BAD_REQUEST = 400;
export const STATUS_CODE_UNAUTHORIZED = 403;
export const STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
export const STATUS_CODE_NOT_FOUND = 404;
